export enum AutomapFlag {
  MapMarkTick = 0,
  MapMarkQuestion,
  MapMarkExclamation,
  MapMarkStar,
  MapMarkCross,
  MapMarkTemple,
  MapMarkKiss,
  MapMarkShovel,
  MapMarkSword,
  MapMarkFlag,
  MapMarkLock,
  MapMarkBag,
  MapMarkSkull,
  MapMarkDollar,
  MapMarkRedNorth,
  MapMarkRedSouth,
  MapMarkRedEast,
  MapMarkRedWest,
  MapMarkGreenNorth,
  MapMarkGreenSouth,
}
