export enum ItemCategory {
  Invalid = 0,
  Ground = 1,
  Container = 2,
  Weapon = 3,
  Ammunition = 4,
  Armor = 5,
  Charges = 6,
  Teleport = 7,
  MagicField = 8,
  Writable = 9,
  Key = 10,
  Splash = 11,
  Fluid = 12,
  Door = 13,
  Deprecated = 14,
  Last = 15,
}
